const UNAUTHORIZATION = "UNAUTHORIZATION"
const USERNAME_FORMAT = "USER_FORMAT"
const PASSWORD_FORMAT = "PASSWORD_FORMAT"
const USERNAME_EXIST = "USERNAME_EXIST"
const PASSWORD_INCORRECT = "PASSWORD_INCORRECT"
const USERNAME_NOT_EXIST = "USERNAME_NOT_EXIST"
const NO_PERMISSION = "NO_PERMISSION"


module.exports = {
  UNAUTHORIZATION,
  USERNAME_FORMAT,
  PASSWORD_FORMAT,
  USERNAME_EXIST,
  PASSWORD_INCORRECT,
  USERNAME_NOT_EXIST,
  NO_PERMISSION,
}